### ISSUE TITLE
Prezentacja

### ISSUE THREAD

**Issue by ddziaduch** [daryush/PHPersDay2019#1]
Cześć, twoja prezentacja bardzo mi się podobała.

Czy możesz ją tutaj dorzucić do repo?

**Comment by daryush** [comment]
Cześć.

Slajdy z prezentecji można znaleźć tutaj: https://www.slideshare.net/DariuszDrobisz/phpers-day-2019

Podrawiam ;)

**Comment by ddziaduch** [comment]
Super, dzięki wielkie @daryush !
